import 'package:cloud_firestore/cloud_firestore.dart';

class QuizModel {
  final String id;
  final String title;
  final String description;
  final String courseId;
  final String? lessonId;
  final List<QuizQuestion> questions;
  final int timeLimit; // in minutes
  final int passingScore; // percentage
  final String difficulty; // easy, medium, hard
  final bool isAutoGenerated;
  final DateTime createdAt;
  final DateTime? updatedAt;

  QuizModel({
    required this.id,
    required this.title,
    required this.description,
    required this.courseId,
    this.lessonId,
    required this.questions,
    required this.timeLimit,
    this.passingScore = 70,
    required this.difficulty,
    this.isAutoGenerated = false,
    required this.createdAt,
    this.updatedAt,
  });

  factory QuizModel.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return QuizModel(
      id: doc.id,
      title: data['title'] ?? '',
      description: data['description'] ?? '',
      courseId: data['courseId'] ?? '',
      lessonId: data['lessonId'],
      questions: (data['questions'] as List<dynamic>?)
          ?.map((e) => QuizQuestion.fromMap(e as Map<String, dynamic>))
          .toList() ?? [],
      timeLimit: data['timeLimit'] ?? 30,
      passingScore: data['passingScore'] ?? 70,
      difficulty: data['difficulty'] ?? 'medium',
      isAutoGenerated: data['isAutoGenerated'] ?? false,
      createdAt: (data['createdAt'] as Timestamp).toDate(),
      updatedAt: data['updatedAt'] != null 
          ? (data['updatedAt'] as Timestamp).toDate() 
          : null,
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'title': title,
      'description': description,
      'courseId': courseId,
      'lessonId': lessonId,
      'questions': questions.map((e) => e.toMap()).toList(),
      'timeLimit': timeLimit,
      'passingScore': passingScore,
      'difficulty': difficulty,
      'isAutoGenerated': isAutoGenerated,
      'createdAt': Timestamp.fromDate(createdAt),
      'updatedAt': updatedAt != null ? Timestamp.fromDate(updatedAt!) : null,
    };
  }
}

class QuizQuestion {
  final String id;
  final String question;
  final List<String> options;
  final int correctAnswer; // index of correct option
  final String explanation;
  final int points;

  QuizQuestion({
    required this.id,
    required this.question,
    required this.options,
    required this.correctAnswer,
    required this.explanation,
    this.points = 1,
  });

  factory QuizQuestion.fromMap(Map<String, dynamic> map) {
    return QuizQuestion(
      id: map['id'] ?? '',
      question: map['question'] ?? '',
      options: List<String>.from(map['options'] ?? []),
      correctAnswer: map['correctAnswer'] ?? 0,
      explanation: map['explanation'] ?? '',
      points: map['points'] ?? 1,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'question': question,
      'options': options,
      'correctAnswer': correctAnswer,
      'explanation': explanation,
      'points': points,
    };
  }
}

class QuizAttempt {
  final String id;
  final String userId;
  final String quizId;
  final Map<String, int> answers; // questionId -> selectedOption
  final int score;
  final int totalQuestions;
  final int correctAnswers;
  final DateTime startedAt;
  final DateTime? completedAt;
  final int timeSpent; // in seconds
  final bool isPassed;

  QuizAttempt({
    required this.id,
    required this.userId,
    required this.quizId,
    required this.answers,
    required this.score,
    required this.totalQuestions,
    required this.correctAnswers,
    required this.startedAt,
    this.completedAt,
    required this.timeSpent,
    required this.isPassed,
  });

  factory QuizAttempt.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return QuizAttempt(
      id: doc.id,
      userId: data['userId'] ?? '',
      quizId: data['quizId'] ?? '',
      answers: Map<String, int>.from(data['answers'] ?? {}),
      score: data['score'] ?? 0,
      totalQuestions: data['totalQuestions'] ?? 0,
      correctAnswers: data['correctAnswers'] ?? 0,
      startedAt: (data['startedAt'] as Timestamp).toDate(),
      completedAt: data['completedAt'] != null 
          ? (data['completedAt'] as Timestamp).toDate() 
          : null,
      timeSpent: data['timeSpent'] ?? 0,
      isPassed: data['isPassed'] ?? false,
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'userId': userId,
      'quizId': quizId,
      'answers': answers,
      'score': score,
      'totalQuestions': totalQuestions,
      'correctAnswers': correctAnswers,
      'startedAt': Timestamp.fromDate(startedAt),
      'completedAt': completedAt != null ? Timestamp.fromDate(completedAt!) : null,
      'timeSpent': timeSpent,
      'isPassed': isPassed,
    };
  }
}
